[package]
name = "starkom-plonk"
version = "2.0.1"
description = "The PLONK arithmetization scheme used in Starkom."
license = "Apache-2.0"
repository = "https://github.com/libernet-xyz/plonk.git"
readme = "README.md"
edition = "2024"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
anyhow = "1.0.103"
primitive-types = "0.14.0"
sha3 = "0.12.0"
starkom-bluesky = "3.2.0"
starkom-ff = "2.3.0"
starkom-pcs = "2.0.1"
starkom-poly = "3.0.1"
